#!/bin/bash
yum update -y
yum -y install httpd
PrivateIP=`curl http://169.254.169.254/latest/meta-data/public-ipv4`
echo "APP EC2 with $PrivateIP " > /var/www/html/index.html
service httpd start
chkconfig httpd on